[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pattern-detection-tokam"
version = "0.1.0"
dependencies = [
]
requires-python = ">=3.8"
authors = [
  {name = "Mansour Benbakoura", email = "mansour.benbakoura@inria.fr"}
]
description = "Pattern detection on TOKAM2D movies"
readme = "README.rst"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]