command:
  - mpiexec
  - -n
  - 1
  - python
  - ${program}
  - ${args}
method: bayes
metric:
  name: sparse_error_l1
  goal: minimize
parameters:
  atom_size:
    value: 85
  eps:
    distribution: log_uniform
    min: -23
    max: -16.1
  offset_type:
    value: mean
  reg:
    distribution: uniform
    min: 0.1
    max: 0.5
  n_atoms:
    value: 10
program: call_dicodile.py