command:
  - mpiexec
  - -n
  - 1
  - python
  - ${program}
  - ${args}
method: bayes
metric:
  name: sparse_error_l1
  goal: minimize
parameters:
  atom_size:
    distribution: categorical
    values:
      - 70
      - 85
  eps:
    distribution: log_uniform
    min: -23
    max: -11.5
  offset_type:
    values:
      - mean
      - mode
  reg:
    distribution: log_uniform
    min: -6.9
    max: -2.3
  n_atoms:
    distribution: int_uniform
    min: 3
    max: 10
program: call_dicodile.py