method: grid
parameters:
  atom_size:
    values:
      - 10
      - 20
      - 50
  n_atoms:
    values:
      - 10
      - 20
  offset_type:
    values:
      - mean
      - median
      - mode
      - none
  reg:
    values:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
  tol:
    values:
      - 0.001
      - 0.0001
      - 1e-05
program: call_dicodile.py
command:
  - mpiexec
  - "-n"
  - 1
  - python
  - ${program}
  - ${args}