name: Build Docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '**.py'
      - '.github/workflows/docs.yaml'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build docs
        uses: ammaraskar/sphinx-action@master